### ISSUE TITLE
Why dproxy not work on my mac?

### ISSUE THREAD

**Issue by haryshi** [danielpaulus/go-ios#108]
it prints below ,any problem of my env or cmd? Thanks a lot.  
I build locally and run :   sudo ./go-ios dproxy

> {"level":"debug","msg":"map[--arg:[] --basedir:\u003cnil\u003e --binary:false --bundleid:\u003cnil\u003e --details:false --env:[] --help:false --nojson:false --output:\u003cnil\u003e --p12file:\u003cnil\u003e --password:\u003cnil\u003e --path:\u003cnil\u003e --pid:\u003cnil\u003e --plist:false --process:\u003cnil\u003e --setlang:\u003cnil\u003e --setlocale:\u003cnil\u003e --stop-at-entry:false --system:false --testrunnerbundleid:\u003cnil\u003e --trace:false --udid:\u003cnil\u003e --verbose:false --version:false --xctestconfig:\u003cnil\u003e \u003capp_path\u003e:\u003cnil\u003e \u003cbundleID\u003e:\u003cnil\u003e \u003chostPort\u003e:\u003cnil\u003e \u003ckey\u003e:[] \u003cprofileId\u003e:\u003cnil\u003e \u003cprofileTypeId\u003e:\u003cnil\u003e \u003ctargetPort\u003e:\u003cnil\u003e apps:false auto:false ax:false date:false debug:false devicename:false devicestate:false diagnostics:false dproxy:true enable:false forward:false image:false info:false install:false kill:false lang:false launch:false list:false listen:false mobilegestalt:false mount:false pair:false pcap:false ps:false readpair:false reboot:false runtest:false runwda:false screenshot:false syslog:false uninstall:false version:false]","time":"2022-02-18T19:25:09+08:00"}
{"level":"debug","msg":"Looking for device ''","time":"2022-02-18T19:25:09+08:00"}
{"level":"info","msg":"no udid specified using first device in list","time":"2022-02-18T19:25:09+08:00","udid":"7978366093cb268c5521e7f07aa511e8aaf5938e"}
{"EnableServiceSSL":true,"Port":65164,"Request":"StartService","Service":"com.apple.mobile.diagnostics_relay","level":"debug","msg":"Service started on device","time":"2022-02-18T19:25:09+08:00"}
INFO[0000] Successfully retrieved pairrecord: 55EA1968-313F-4B8B-BDF8-EE20A7AADC70 for device 7978366093cb268c5521e7f07aa511e8aaf5938e 
INFO[0000] Moving socket /var/run/usbmuxd to /var/run/usbmuxd.f5c85170-dfc4-4a07-bd6c-ad6eeae9e1dd.real_socket 
INFO[0005] Creating binary dump of all communication between MAC OS and debugproxy at: dump-2022.02.18-11.25.09.461/connection-#1-2022.02.18-11.25.14.242/bindump-hostservice-to-proxy.txt 
INFO[0005] Creating binary dump of all communication between MAC OS and debugproxy at: dump-2022.02.18-11.25.09.461/connection-#2-2022.02.18-11.25.14.244/bindump-hostservice-to-proxy.txt 
INFO[0005] Creating binary dump of all communication between MAC OS and debugproxy at: dump-2022.02.18-11.25.09.461/connection-#3-2022.02.18-11.25.14.245/bindump-hostservice-to-proxy.txt 
INFO[0005] Creating binary dump of all communication between MAC OS and debugproxy at: dump-2022.02.18-11.25.09.461/connection-#4-2022.02.18-11.25.14.245/bindump-hostservice-to-proxy.txt 
panic: ServiceInfo for port: 48900 not found, this is a bug :-)reqheader: {Length:348 Version:1 Request:8 Tag:0} repayload: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d38223f3e0a3c21444f435459504520706c697374205055424c494320222d2f2f4170706c652f2f44544420504c49535420312e302f2f454e222022687474703a2f2f7777772e6170706c652e636f6d2f445444732f50726f70657274794c6973742d312e302e647464223e0a3c706c6973742076657273696f6e3d22312e30223e0a3c646963743e0a093c6b65793e44657669636549443c2f6b65793e0a093c696e74656765723e3139313c2f696e74656765723e0a093c6b65793e4d657373616765547970653c2f6b65793e0a093c737472696e673e436f6e6e6563743c2f737472696e673e0a093c6b65793e506f72744e756d6265723c2f6b65793e0a093c696e74656765723e34383930303c2f696e74656765723e0a3c2f646963743e0a3c2f706c6973743e0a

goroutine 24 [running]:
github.com/danielpaulus/go-ios/ios/debugproxy.handleConnect({{0x15c, 0x1, 0x8, 0x0}, {0xc0000aa580, 0x14c, 0x14c}}, 0x3ed, 0xc00057a280, 0xc00038a0c0, ...)
	/Users/jinrong.sjr/desktop/reverse/go-ios/ios/debugproxy/muxhandler.go:104 +0x3f4
github.com/danielpaulus/go-ios/ios/debugproxy.proxyUsbMuxConnection(0xc00057a280, 0xc00038a0c0, 0xc00038a0d8)
	/Users/jinrong.sjr/desktop/reverse/go-ios/ios/debugproxy/muxhandler.go:37 +0xe65
created by github.com/danielpaulus/go-ios/ios/debugproxy.startProxyConnection
	/Users/jinrong.sjr/desktop/reverse/go-ios/ios/debugproxy/debugproxy.go:160 +0x6d6

**Comment by danielpaulus** [comment]
sometimes it can be a bit flaky, is it reproducible?
If so, can you please share the entire dump somehow?
