### ISSUE TITLE
How to get the CrashReport

### ISSUE THREAD

**Issue by yunhailu** [danielpaulus/go-ios#109]
I can see function idevicecrashreport in libimobiledevice.  How could  I get iphone  crash report with go-ios.

**Comment by yunhailu** [comment]
Setting -> Privacy -> Analysis -> Analysis Data

**Comment by danielpaulus** [comment]
Check the PR :-D 
I just need to add some docs and somehow test on windows. There is probably some issues because of "\" in windows paths. 🙄 windows..
