### ISSUE TITLE
Can we have go-ios as dependency rather then downloading an executabel?

### ISSUE THREAD

**Issue by deepakarorawins** [danielpaulus/go-ios#115]
To use go-ios it will be required to download the executable and keep that in particular repository, that will increase the size of client repository. And also it is harder to maintain the versions. 

Can we have go-ios as dependency?

**Comment by danielpaulus** [comment]
Not entirely sure what you mean, if you want to use it in another golang project you can totally do that. 
Here's an example where I did it: https://github.com/danielpaulus/go-ios-api
Does that help?

**Comment by deepakarorawins** [comment]
Thanks for quick response.
I want to use this "go-ios" in my Appium-Java-Maven project. So I was thinking to have "go-ios" as a maven dependency. Or as a brew install or npm install.

As of now I have to keep copy of "go-ios" v1.0.49 in my project.

**Comment by danielpaulus** [comment]
Ah now I understand, hmm I guess it would be pretty easy to make it brew installable. Let me check it out.

**Comment by danielpaulus** [comment]
`npm install -g go-ios` should work now. I will hook it up with the CI to auto publish new version in the future.

**Comment by deepakarorawins** [comment]
Thanks for the quick solution.
However could you please fix it for Mac M1 also?

Below is the output for **npm install -g go-ios** : - 
deepakarora@Deepaks-MacBook-Pro ~ % npm install -g go-ios   
npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/go-ios
npm ERR! command failed
npm ERR! command sh -c node postinstall.js install
npm ERR! Installation is not supported for this architecture: arm64
npm ERR! Invalid inputs

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deepakarora/.npm/_logs/2022-04-14T00_00_30_671Z-debug-0.log
deepakarora@Deepaks-MacBook-Pro ~ % 


**Below is the log: -** 
0 verbose cli /opt/homebrew/Cellar/node/17.6.0_1/bin/node /opt/homebrew/bin/npm
1 info using npm@8.6.0
2 info using node@v17.6.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/deepakarora/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 6ms
18 timing npm:load:configload Completed in 6ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install go-ios
22 verbose argv "install" "--global" "go-ios"
23 timing npm:load:setTitle Completed in 2ms
24 timing config:load:flatten Completed in 1ms
25 timing npm:load:display Completed in 2ms
26 verbose logfile logs-max:10 dir:/Users/deepakarora/.npm/_logs
27 verbose logfile /Users/deepakarora/.npm/_logs/2022-04-14T00_00_30_671Z-debug-0.log
28 timing npm:load:logFile Completed in 2ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 13ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 2ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest go-ios@*
39 http fetch GET 200 https://registry.npmjs.org/go-ios 6ms (cache hit)
40 silly placeDep ROOT go-ios@1.0.56 OK for:  want: *
41 silly fetch manifest mkdirp@^1.0.4
42 http fetch GET 200 https://registry.npmjs.org/mkdirp 2ms (cache hit)
43 timing idealTree:#root Completed in 13ms
44 silly placeDep node_modules/go-ios mkdirp@1.0.4 OK for: go-ios@1.0.56 want: ^1.0.4
45 timing idealTree:node_modules/go-ios Completed in 1ms
46 timing idealTree:node_modules/go-ios/node_modules/mkdirp Completed in 0ms
47 timing idealTree:buildDeps Completed in 14ms
48 timing idealTree:fixDepFlags Completed in 1ms
49 timing idealTree Completed in 18ms
50 timing reify:loadTrees Completed in 20ms
51 timing reify:diffTrees Completed in 0ms
52 silly reify moves {}
53 timing reify:retireShallow Completed in 0ms
54 timing reify:createSparse Completed in 1ms
55 timing reify:loadBundles Completed in 0ms
56 silly audit bulk request { 'go-ios': [ '1.0.56' ], mkdirp: [ '1.0.4' ] }
57 timing reifyNode:node_modules/go-ios/node_modules/mkdirp Completed in 136ms
58 timing reifyNode:node_modules/go-ios Completed in 167ms
59 timing reify:unpack Completed in 167ms
60 timing reify:unretire Completed in 0ms
61 timing build:queue Completed in 1ms
62 timing build:link:node_modules/go-ios/node_modules/mkdirp Completed in 1ms
63 timing build:link Completed in 1ms
64 info run go-ios@1.0.56 postinstall node_modules/go-ios node postinstall.js install
65 info run go-ios@1.0.56 postinstall { code: 1, signal: null }
66 timing reify:rollback:createSparse Completed in 3ms
67 timing reify:rollback:retireShallow Completed in 0ms
68 timing command:install Completed in 231ms
69 verbose stack Error: command failed
69 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
69 verbose stack     at ChildProcess.emit (node:events:527:28)
69 verbose stack     at maybeClose (node:internal/child_process:1090:16)
69 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
69 verbose stack     at Socket.emit (node:events:527:28)
69 verbose stack     at Pipe.<anonymous> (node:net:688:12)
70 verbose pkgid go-ios@1.0.56
71 verbose cwd /Users/deepakarora
72 verbose Darwin 21.4.0
73 verbose node v17.6.0
74 verbose npm  v8.6.0
75 error code 1
76 error path /opt/homebrew/lib/node_modules/go-ios
77 error command failed
78 error command sh -c node postinstall.js install
79 error Installation is not supported for this architecture: arm64
79 error Invalid inputs
80 verbose exit 1
81 timing npm Completed in 268ms
82 verbose unfinished npm timer reify 1649894430708
83 verbose unfinished npm timer reify:audit 1649894430732
84 verbose unfinished npm timer auditReport:getReport 1649894430732
85 verbose unfinished npm timer reify:build 1649894430900
86 verbose unfinished npm timer build 1649894430900
87 verbose unfinished npm timer build:deps 1649894430900
88 verbose unfinished npm timer build:run:postinstall 1649894430902
89 verbose unfinished npm timer build:run:postinstall:node_modules/go-ios 1649894430902
90 verbose code 1
91 error A complete log of this run can be found in:
91 error     /Users/deepakarora/.npm/_logs/2022-04-14T00_00_30_671Z-debug-0.log

**Comment by danielpaulus** [comment]
I should have tested on M1 :-D 
I will fix it soon :-) Thanks for reporting this.

**Comment by danielpaulus** [comment]
https://github.com/danielpaulus/go-ios/pull/116

**Comment by danielpaulus** [comment]
should work now.

**Comment by deepakarorawins** [comment]
Great, It worked.
Thank you so much for your quick help.
