### ISSUE TITLE
incomplete deviceinfo

### ISSUE THREAD

**Issue by SolskGaer** [danielpaulus/go-ios#16]
I tried this repo and compared the output of `ios info` with ideviceinfo and found that the results are different, many values can be got by ideviceinfo but not `ios info`, also, `ios info` is not able to query by the keys listed in ideviceinfo help.

**Comment by danielpaulus** [comment]
I will publish a major update that includes running UI tests, launching and killing apps and a few things more this week. 
Fix for the info part will come as well.

**Comment by danielpaulus** [comment]
Fixed
