### ISSUE TITLE
Do you support setting mobile phone language? Does it support setting WLAN network proxy?

### ISSUE THREAD

**Issue by timwang-ai** [danielpaulus/go-ios#162]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by danielpaulus** [comment]
you can use `ios lang [--setlocale=<locale>] [--setlang=<newlang>] [options]    Sets or gets the Device language`
for setting the language. 
for setting wlan network proxy you need a supervised device and and
then you can use `ios httpproxy <host> <port> [<user>] [<pass>] --p12file=<orgid> [--password=<p12password>] set global http proxy on supervised device. Use the password argument or set the environment variable 'P12_PASSWORD'`

**Comment by timwang-ai** [comment]
thanks, bro.
