### ISSUE TITLE
The version of the developer disk image does not match.

### ISSUE THREAD

**Issue by k-inoway** [danielpaulus/go-ios#167]
**Describe the bug**
Thank you for the great project.

 I ran the command `ios image auto`. My device is on iOS 15.6.1, but the developer disk image downloaded iOS 15.4. If no matching version is found, an error should be returned.

Also, there are no versions 15.6, 15.6.1, or 16.0 on this haikieu's Github.

The following github is frequently updated.
https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images

**To Reproduce**
1. run `ios image auto`
2. Version 15.4 will be downloaded.

**Expected behavior**
If no matching version is found, an error should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/40589931/186593895-9c9aad25-82af-44aa-955a-e33aedbed4f5.png)

**Desktop (please complete the following information):**
 - OS: Windows10 20H2

**Smartphone (please complete the following information):**
 - Device: iPhone12 mini
 - OS: iOS 15.6.1

**Comment by Valkhes** [comment]
Got the same problem with iOS 16.0, the last developer image available seems to be 15.4, and it tries to mount 15.4. 

Note that it's not a problem if you already have the developer image as you can use ios image mount --path=<developer_image_dmg_path>

**Comment by danielpaulus** [comment]
Nice, I will change to the other repo! Thanks for the tip.

**Comment by danielpaulus** [comment]
Ok, should be fixed with the next version. It should work fine now.

**Comment by nanoscopic** [comment]
You really shouldn't use any github repo of developer images. The best is to use the latest available Xcode available directly from Apple and extract the images from there. Anything else and you are asking for trouble.
