### ISSUE TITLE
If the ios httpproxy remove does not take effect immediately, how can it be resolved?

### ISSUE THREAD

**Issue by timwang-ai** [danielpaulus/go-ios#171]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nanoscopic** [comment]
You haven't provided all the requested context needed. Don't just leave the example template of details needed as the example. You are defeating the point of it.

When/where/how are you seeing "httpproxy remove does not take effect immediately"?
