### ISSUE TITLE
archiver.ArchiveBin fail

### ISSUE THREAD

**Issue by lilili87222** [danielpaulus/go-ios#173]
`

func gettttConfig() map[string]any {
	var option = make(map[string]any)
	option["name"] = "james"
	option["age"] = 20
	children := []string{"abc", "def", "ok"}
	option["children"] = children
	data, err := archiver.ArchiveBin(option)
	if err != nil {
		fmt.Printf("encode data %v fail %v", data, err)
	}
	return option
}

`

encode fail

**Comment by danielpaulus** [comment]
Should be working fine now. Let me know if you still encounter issues.

**Comment by lilili87222** [comment]
encode a dic but decode return a array,not a dic
