### ISSUE TITLE
Error when building on armv7l

### ISSUE THREAD

**Issue by CedricCouton** [danielpaulus/go-ios#175]
**Describe the bug**
If we try to build on armv7l we have this error :
ios/dtx_codec/connection.go:174:31: cannot use 4294967295 (untyped int constant) as int value in argument to dtxConn.activeChannels.Store (overflows)

**To Reproduce**
compile on armv7l

**Expected behavior**
this should compile

**Comment by danielpaulus** [comment]
Thanks for the report and even more so for the fix!
