### ISSUE TITLE
Does go-ios support port forwarding of wda? Run XCTest and listen on pc 8200 port forward to mobile 8100 service

### ISSUE THREAD

**Issue by timwang-ai** [danielpaulus/go-ios#186]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by timwang-ai** [comment]
ios runwda Does it support designated ports?

**Comment by 7999** [comment]
hi, did you find a way to do that? I also have a same requirement, run wda and listen on pc with specific port forward to mobile 8100 port
