### ISSUE TITLE
Panic | interface conversion: interface {} is string, not map[string]interface {}

### ISSUE THREAD

**Issue by akshatlambdatest** [danielpaulus/go-ios#207]
**Describe the bug**
Intermittently observing panic is occurring with the error `interface conversion: interface {} is string, not map[string]interface {}`
Stack trace
```
github.com/danielpaulus/go-ios@v1.0.24/ios/screenshotr/screenshot.go:76
```

**To Reproduce**
1. Take a screenshot from an ios device

**Expected behavior**
The panic should be handled and the correct error returned from the function.

**Comment by shamanec** [comment]
Sorry if that is a stupid question but have you tried the latest version? v1.0.24 is quite old

**Comment by akshatlambdatest** [comment]
Haven't tried the latest version but the buggy code is still present in main branch https://github.com/danielpaulus/go-ios/blob/main/ios/screenshotr/screenshot.go#L76

**Comment by danielpaulus** [comment]
I'll tackle this today. The current implementation is very basic and definitely needs improvements.
