### ISSUE TITLE
`ios runtest`: allow for passing two bundle identifiers explicitly

### ISSUE THREAD

**Issue by bartekpacia** [danielpaulus/go-ios#224]
Hi @danielpaulus, first of all, thanks a ton for this amazing project. It's just incredible.

I have a problem with the `ios runtest` command, which by default accepts only the bundle ID of the _app under test_, and attempts to create the bundle ID of the _test runner app_ by appending `UITests.xctrunner` to it ([source](https://github.com/danielpaulus/go-ios/issues/51#issuecomment-903085149)). Unfortunately, that's not always the case.

```console
$ ios apps --list | grep pl.leancode.patrol
{"level":"info","msg":"no udid specified using first device in list","time":"2023-01-30T16:32:34+01:00","udid":"00008101-001611D026A0001E"}
pl.leancode.patrol.Example Example 1.0.0
pl.leancode.patrol.Example.RunnerUITests.xctrunner RunnerUITests-Runner 1.0
```

Because of this, I can't run UI tests in my app.

I'd be happy if the `ios runtest` accepted a second, _optional_ bundle ID, so I could do:

```console
$ ios runtest pl.leancode.patrol.Example pl.leancode.patrol.Example.RunnerUITests.xctrunner
```

**Comment by bartekpacia** [comment]
Hi @shamanec, thank you :) I'll check it out soon!

BTW, since you're a collaborator on this repo, could you review #225? :)

**Comment by bartekpacia** [comment]
What's the `xctestConfigName` and where should I look for it?

**Comment by shamanec** [comment]
I can't remember exactly where to find it in Xcode and I don't have a Macbook available :( I think you might be able to find the proper file in `/YourXCUITest.app/PlugIns/SomeName.xctest` where `YourXCUITest.app` is the testing package built by Xcode. Then you can provide `SomeName.xctest` as `xctestConfigName`

**Comment by shamanec** [comment]
Here is a screenshot from the WebDriverAgent app that I am using:
![image](https://user-images.githubusercontent.com/60219580/220127941-610ccd5f-5493-42e8-8478-52a92832a58c.png)

**Comment by bartekpacia** [comment]
This works as well :)

```
./go-ios runtest \
   --bundleid pl.leancode.patrol.Example
  --testrunnerbundleid pl.leancode.patrol.Example.RunnerUITests.xctrunner \
  --xctestconfig RunnerUITests.xctest
```

If I may nitpick, I'd prefer to have two of these options named:
- `--bundle-id`
- `test-runner-bundle-id`

:)

**Comment by shamanec** [comment]
Changed to `--bundle-id`, `--test-runner-bundle-id` and `--xctest-config`, let me know if all is good

**Comment by bartekpacia** [comment]
Sure, that sounds great. And thank you for helping with merges!

I admire this project and what @danielpaulus did here. It looks way better to me than [ios-deploy](https://github.com/ios-control/ios-deploy). `ios-deploy` is basically a single 3000-line Objective-C file that is 10 years old. It's pretty flaky also.

Currently [we](https://github.com/leancodepl) use `ios-deploy` in [our new testing framework for Flutter apps](https://github.com/leancodepl/patrol), because that was the fastest (but dirty way) to implement some important features. I'm thinking about migrating to `go-ios`, though :) 

If we decide to use `go-ios`, I'll for sure ask management if we could support the development of this lib, or if I could spend some time helping to maintain it :)

**Comment by bartekpacia** [comment]
Fixed by #229 :)

**Comment by bartekpacia** [comment]
Note to myself:

`go-ios` works very nice in my use case

```
ios debug build/ios_integ/Build/Products/Debug-iphoneos/Runner.app

**Comment by shamanec** [comment]
Nice! Daniel is always excited to see more adopters 😅 I'll merge this change but unfortunately I cannot help with the github actions PR because I don't have much experience there. You can try tagging Daniel and see if he could find some time to approve it :) Do not hesitate to add more issues or enhancement requests, I'll try to help out as well if I can!

**Comment by danielpaulus** [comment]
Guys I am close to crying here, a PR merged without me doing anything. This is so beautiful! Thank you so much for the effort! I am currently working on a new project to boost go-ios to the next level, that is why I am a bit silent. Sorry for that, I am finally getting somewhere though. Will update in a couple of weeks.
