### ISSUE TITLE
Standarize and enforce code formatting

### ISSUE THREAD

**Issue by bartekpacia** [danielpaulus/go-ios#232]
It'd be nice if the project used (thus, enforced) standardized code formatting, e.g with a tool such as `gofmt` (or even better, `gofumpt`, [which is a stricter version and widely used variant of `gofmt`](https://github.com/mvdan/gofumpt)).

**Describe the solution you'd like**

Format whole code with a formatted and enforce consistent code formatting for new PRs.

**Comment by danielpaulus** [comment]
Hm I think making this change is not strictly necessary and will cause a lot of conflicts for the people forking this repo. If you consider there are 94 forks, I don't really want to merge this right now. 
Adding gofmt to the CI potentially yes, but I am not convinced to merge gofumpt.

**Comment by bartekpacia** [comment]
Sure, gofmt is also great :) I will modify my PR #234 to use gofmt instead of gofumpt.

Regarding the forks, I'm pretty sure it's okay to not care about them. In my experience, most of people who click "fork" have no intention of contributing whatsoever - I guess they think of "fork" similarly to "star" :)

**Comment by nanoscopic** [comment]
Forks matter. Forcing gofmt use is gatekeeping. Any of this sort of stuff will discourage PRs.

If formatting it desired, it should be a request to PR creators to run `go fmt` on their code before submitting their PR.
