### ISSUE TITLE
Bowing out

### ISSUE THREAD

**Issue by nanoscopic** [danielpaulus/go-ios#239]
It is clear this project has reached enough popularity to draw a certain crowd of people that I want nothing to do with.

I collaborated, sponsored, and helped in research for a lot of the initial knowledge related to this project, and I find the trash coming from some of the new members to be offensive.

You all want to trash this repo and turn it into a pile of junk? Be my guests. I'll stick with my fork and I no longer want to be thought of when it comes to this project.

@danielpaulus Feel free to either comment on this issue if you wish or just close it out. I am simply stating it so whoever might care is aware.

**Comment by danielpaulus** [comment]
I am sad to see you leave of course. Thanks for all the help and insights you provided! 
If you ever change your mind, you will be always welcome.
