### ISSUE TITLE
How to use httpproxy?

### ISSUE THREAD

**Issue by Haif-07** [danielpaulus/go-ios#281]
![image](https://github.com/danielpaulus/go-ios/assets/58282852/2d3acef4-a115-4e2d-bc13-2244089fe1a5)

Replacing software.sslmate.com/src/go-pkcs12 can solve the above error.
But executing the command again appears：
{"err":"escalate response had error map[Status:CertificateRejected]","level":"fatal","msg":"failed","time":"2023-09-06T15:52:57+08 :00"}

**Comment by Dantee296** [comment]
@Haif-07 how did u fix it ?
