### ISSUE TITLE
Move pair command from branch go-ios-old

### ISSUE THREAD

**Issue by soulgalore** [danielpaulus/go-ios#31]
Hi @danielpaulus and thanks for this great project!

One of the many problems I've had with iOS devices is pairing. I've a setup where Xcode says my device is paired and the Safari webdriver says it is not, so I wanna try to pair my phone with go-ios but it seems that functionality isn't there yet:
```
 ./ios pair  
not yet copied from branch go-ios-old
```

If that's easy to fix it would be super to have it the current branch.

Best
Peter

**Comment by danielpaulus** [comment]
There is a PR open, I will try to merge it this weekend.

**Comment by danielpaulus** [comment]
Should work now :-)

**Comment by soulgalore** [comment]
Thank you @danielpaulus !
