### ISSUE TITLE
ARM64 binary for NPM install to work

### ISSUE THREAD

**Issue by serbyxp** [danielpaulus/go-ios#318]
**Is your feature request related to a problem? Please describe.**
Problem installing go-ios from NPM.
I believe there is no binary for the NPM install to complete the postinstall.js script.
It would be nice for home / dev machines running on arm64 (dev / raspberry pi boards) that are running local / containerized node.js to just build without extra steps (installing go etc..)

**Describe the solution you'd like**
NPM install that works on ARM64

**Describe alternatives you've considered**
--install go on arm64 device-- ref. https://go.dev/doc/install
`wget https://go.dev/dl/go1.21.5.linux-arm64.tar.gz`
`rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz`
`git clone https://github.com/danielpaulus/go-ios.git,`
`go build` | `go run main.go`
...

**Additional context**
 sudo npm install -g go-ios

npm ERR! code 1

npm ERR! path /usr/lib/node_modules/go-ios

npm ERR! command failed

npm ERR! command sh -c node postinstall.js install

npm ERR! Copying the relevant binary for your platform linux

npm ERR! Error: Command failed: cp ./dist/go-ios-linux-undefined_linux_undefined/ios ./bin/ios

npm ERR! cp: cannot stat './dist/go-ios-linux-undefined_linux_undefined/ios': No such file or directory

npm ERR! 

npm ERR!     at ChildProcess.exithandler (node:child_process:422:12)

npm ERR!     at ChildProcess.emit (node:events:514:28)

npm ERR!     at maybeClose (node:internal/child_process:1105:16)

npm ERR!     at Socket.<anonymous> (node:internal/child_process:457:11)

npm ERR!     at Socket.emit (node:events:514:28)

npm ERR!     at Pipe.<anonymous> (node:net:337:12) {

npm ERR!   code: 1,

npm ERR!   killed: false,

npm ERR!   signal: null,

**npm ERR!   cmd: 'cp ./dist/go-ios-linux-undefined_linux_undefined/ios ./bin/ios'**

npm ERR! }

**npm ERR! Downloaded binary does not contain the binary specified in configuration - ios**

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-22T00_28_25_877Z-debug-0.log

**Comment by muvaf** [comment]
@danielpaulus Just opened a PR to fix this issue https://github.com/danielpaulus/go-ios/pull/527
