### ISSUE TITLE
Screenshot streaming was a very useful feature, which is broken with iOS17

### ISSUE THREAD

**Issue by revathySV** [danielpaulus/go-ios#411]
**Is your feature request related to a problem? Please describe.**
Screenshot streaming of the connected iOS device won't work anymore

**Describe the solution you'd like**
Requesting adaptation of the screenshot service to include the RSD related changes for iOS17  as it has been done for instruments services

**Describe alternatives you've considered**
Considered other libraries that provide this. Would like to go with this all-in-1 library for my current usecases

**Comment by danielpaulus** [comment]
Fixed now thanks to @shamanec
