### ISSUE TITLE
iOS17.0 tunnel start error

### ISSUE THREAD

**Issue by panderman** [danielpaulus/go-ios#413]
### First of all, this is a great project, thank you, but I have a problem while using goland debug.

When I use an iPad with iPadOS 17.5.1, the trunnel start command works fine, but when I use an xs max with 17.0, the command execution fails.

Computer：Macbook Pro M1
Device：iPhone XS Max 17.0
Command：tunnel start
Run with sudo

Debug logs：

> API server listening at: 127.0.0.1:57070
{"level":"info","msg":"Set Debug mode","time":"2024-06-18T00:21:08+08:00"}
{"level":"debug","msg":"map[--address:\u003cnil\u003e --all:false --apps:false --arg:[] --basedir:\u003cnil\u003e --binary:false --bundle-id:\u003cnil\u003e --bundleid:\u003cnil\u003e --certfile:\u003cnil\u003e --details:false --dstPath:\u003cnil\u003e --enable-post-restart:false --env:[] --filesharing:false --font:\u003cnil\u003e --force:false --gpxfilepath:\u003cnil\u003e --help:false --iface:\u003cnil\u003e --lang:false --lat:\u003cnil\u003e --list:false --locale:false --log-output:\u003cnil\u003e --lon:\u003cnil\u003e --mode:\u003cnil\u003e --nojson:false --orgname:\u003cnil\u003e --output:\u003cnil\u003e --p12file:\u003cnil\u003e --pair-record-path:\u003cnil\u003e --password:\u003cnil\u003e --path:\u003cnil\u003e --pid:\u003cnil\u003e --plist:false --port:\u003cnil\u003e --pretty:false --process:\u003cnil\u003e --r:false --rsd-port:\u003cnil\u003e --setlang:\u003cnil\u003e --setlocale:\u003cnil\u003e --skip:[] --skip-all:false --srcPath:\u003cnil\u003e --stop-at-entry:false --stream:false --system:false --test-runner-bundle-id:\u003cnil\u003e --test-to-run:[] --test-to-skip:[] --testrunnerbundleid:\u003cnil\u003e --trace:false --tunnel-info-port:\u003cnil\u003e --udid:00008020-000964C82199002E --verbose:true --version:false --wait:false --xctest-config:\u003cnil\u003e --xctestconfig:\u003cnil\u003e 12h:false 24h:false \u003capp_path\u003e:\u003cnil\u003e \u003cbundleID\u003e:\u003cnil\u003e \u003ccwd\u003e:\u003cnil\u003e \u003chost\u003e:\u003cnil\u003e \u003chostPort\u003e:\u003cnil\u003e \u003ckey\u003e:[] \u003cpass\u003e:\u003cnil\u003e \u003cpattern\u003e:\u003cnil\u003e \u003cport\u003e:\u003cnil\u003e \u003cprofileFile\u003e:\u003cnil\u003e \u003cprofileId\u003e:\u003cnil\u003e \u003cprofileName\u003e:\u003cnil\u003e \u003cprofileTypeId\u003e:\u003cnil\u003e \u003csrcpattern\u003e:\u003cnil\u003e \u003ctarget\u003e:\u003cnil\u003e \u003ctargetPort\u003e:\u003cnil\u003e \u003cuser\u003e:\u003cnil\u003e activate:false add:false apps:false assistivetouch:false auto:false ax:false batterycheck:false cp:false crash:false create-cert:false date:false debug:false devicename:false devicestate:false devmode:false diagnostics:false disable:false diskspace:false display:false dproxy:false enable:false erase:false forward:false fsync:false get:false httpproxy:false image:false info:false install:false instruments:false ip:false kill:false lang:false launch:false list:false listen:false lockdown:false ls:false mkdir:false mobilegestalt:false mount:false notifications:false pair:false pcap:false prepare:false printskip:false profile:false ps:false pull:false push:false readpair:false reboot:false remove:false resetlocation:false rm:false runtest:false runwda:false screenshot:false setlocation:false setlocationgpx:false start:true syslog:false timeformat:false toggle:false tree:false tunnel:true uninstall:false version:false voiceover:false zoomtouch:false]","time":"2024-06-18T00:21:08+08:00"}
{"level":"debug","msg":"Looking for device '00008020-000964C82199002E'","time":"2024-06-18T00:21:08+08:00"}
{"level":"info","msg":"Tunnel server started","time":"2024-06-18T00:21:08+08:00"}
{"level":"info","msg":"start tunnel","time":"2024-06-18T00:21:09+08:00","udid":"e1c5c5d07d9c372bcd1ce6be99ad13bd55bfbb3a"}
{"EnableServiceSSL":true,"Port":59308,"Request":"StartService","Service":"com.apple.internal.devicecompute.CoreDeviceProxy","level":"debug","msg":"Service started on device","time":"2024-06-18T00:21:09+08:00"}
{"level":"info","msg":"connect to lockdown tunnel endpoint on device","time":"2024-06-18T00:21:09+08:00"}
{"level":"info","msg":"start tunnel","time":"2024-06-18T00:21:09+08:00","udid":"00008020-000964C82199002E"}
{"level":"info","msg":"ManualPairAndConnectToTunnel: starting manual pairing and tunnel connection, dont forget to stop remoted first with 'sudo pkill -SIGSTOP remoted' and run this with sudo.","time":"2024-06-18T00:21:09+08:00"}
{"err":"udp6: failed to join any of these interfaces: [{2 1280 gif0  pointtopoint|multicast}]","interface":"gif0","level":"debug","msg":"failed to initialize resolver","time":"2024-06-18T00:21:09+08:00"}
{"err":"udp6: failed to join any of these interfaces: [{3 1280 stf0  0}]","interface":"stf0","level":"debug","msg":"failed to initialize resolver","time":"2024-06-18T00:21:09+08:00"}
{"err":"udp6: failed to join any of these interfaces: [{4 0 XHC1  0}]","interface":"XHC1","level":"debug","msg":"failed to initialize resolver","time":"2024-06-18T00:21:09+08:00"}
{"err":"udp6: failed to join any of these interfaces: [{5 0 XHC0  0}]","interface":"XHC0","level":"debug","msg":"failed to initialize resolver","time":"2024-06-18T00:21:09+08:00"}
{"err":"udp6: failed to join any of these interfaces: [{10 1500 en1 36:c3:a3:f7:52:00 up|broadcast|multicast|running}]","interface":"en1","level":"debug","msg":"failed to initialize resolver","time":"2024-06-18T00:21:09+08:00"}
{"err":"udp6: failed to join any of these interfaces: [{11 1500 en2 36:c3:a3:f7:52:04 up|broadcast|multicast|running}]","interface":"en2","level":"debug","msg":"failed to initialize resolver","time":"2024-06-18T00:21:09+08:00"}
ncm._remoted._tcp.local.2024/06/18 00:21:09 ERROR failed to connect to remote service discovery error="NewWithAddrPort: failed to create xpc connection: CreateXpcConnection: failed to initialize xpc connection: initializeXpcConnection: failed to decode message: DecodeMessage: failed to read magic number: ReadClientServerStream: readDataFrame: got RST frame with error code: INTERNAL_ERROR" address=fe80::cff:7eff:fe1e:4b61%en9

Then i tried the code of pymobiledevice3 and ran: sudo python3 -m pymobiledevice3 remote start-tunnel. The service can be started normally. 

I am not malicious. I just want to say that there may be some problems with the tunnel strart command that have not yet been discovered. I look forward to your reply.

**Comment by panderman** [comment]
I gotta do `sudo pkill -SIGSTOP remoted` to pause the remoted process.
`sudo pkill -SIGCONT remoted` is used to restart the remoted process if needed :)

**Comment by luoxiao1008** [comment]
how to  do "sudo pkill -SIGSTOP remoted" on windows?

**Comment by moonlight824** [comment]
> how to do "sudo pkill -SIGSTOP remoted" on windows?


same question. have you solved it?
