### ISSUE TITLE
remotely turning on iOS screen

### ISSUE THREAD

**Issue by petemyron** [danielpaulus/go-ios#42]
Awesome library--thanks for making this! 

I'm messing with some iPhones remotely and can't quite complete some WebDriverAgent initialization until the screen is on. I played with this a bit and found that I can turn the screen on with `go-ios launch com.apple.Preferences` (edit: or `com.apple.Home`, etc.). I hope that helps others. I'd prefer that the behavior be closer to the power button being pressed instead of launching something.

Assume pairing is complete, can you think of a better way to force the screen to come on with this library? It feels like a hack.

**Comment by danielpaulus** [comment]
./go-ios launch com.apple.springboard

Is a bit less hacky, as it basically launches springboard only :-D

**Comment by danielpaulus** [comment]
moving it to the new QA feature of github discussions to clean the issues page.
https://github.com/danielpaulus/go-ios/discussions/88
