### ISSUE TITLE
Is it possible to recognize multiple devices using the iOS tunnel start command?

### ISSUE THREAD

**Issue by DragonClub** [danielpaulus/go-ios#429]
I am using it on windows os.

However, when I do ios tunnel start, only one tunnel is created when two iOS devices are connected. Is there a way to do this?
The command result is as follows:

C:\Users\Administrator\Downloads\go-ios-win>ios tunnel start --udid=aaaa
{"level":"warning","msg":"go-ios agent is not running. You might need to start it with 'ios tunnel start' for ios17+. Use ENABLE_GO_IOS_AGENT=yes for experimental daemon mode.","time ":"2024-07-16T11:59:14+09:00"}
{"level":"info","msg":"Tunnel server started","time":"2024-07-16T11:59:14+09:00"}
{"level":"info","msg":"start tunnel","time":"2024-07-16T11:59:15+09:00","udid":"xxxx"}
{"level":"info","msg":"connect to lockdown tunnel endpoint on device","time":"2024-07-16T11:59:15+09:00"}
2024/07/16 11:59:15 Using existing driver 0.14
2024/07/16 11:59:15 Creating adapter
{"level":"info","msg":"windows cmd","time":"2024-07-16T11:59:18+09:00"}
{"level":"info","msg":"C:\\Windows\\system32\\netsh.exe interface ipv6 set address tun0 fddd:3a5f:af31::2/64","time":"2024 -07-16T11:59:18+09:00"}
{"level":"info","msg":"batch size: 1 mtu:1280","time":"2024-07-16T11:59:18+09:00"}
{"level":"info","msg":"start tunnel","time":"2024-07-16T11:59:18+09:00","udid":"aaaa"}
{"level":"info","msg":"ManualPairAndConnectToTunnel: starting manual pairing and tunnel connection, dont forget to stop remoted first with 'sudo pkill -SIGSTOP remoted' and run this with sudo.","time":" 2024-07-16T11:59:18+09:00"}
2024/07/16 11:59:18 Removed orphaned adapter "tun0 1"
{"error":"ManualPairAndConnectToTunnel: failed to find device ethernet interface: context deadline exceeded","level":"warning","msg":"failed to start tunnel","time":"2024-07-16T11: 59:28+09:00","udid":"aaaa"}
{"level":"info","msg":"start tunnel","time":"2024-07-16T11:59:28+09:00","udid":"aaaa"}
{"level":"info","msg":"ManualPairAndConnectToTunnel: starting manual pairing and tunnel connection, dont forget to stop remoted first with 'sudo pkill -SIGSTOP remoted' and run this with sudo.","time":" 2024-07-16T11:59:28+09:00"}

And is there no way to specify the udid like "ios tunnel start --udid=aaaa"?

**Comment by DragonClub** [comment]
You can do this by disconnecting the second device and connecting it again. I don't know if that's true.

**Comment by gi19901212** [comment]
> You can do this by disconnecting the second device and connecting it again. I don't know if that's true.

May I ask if there is a better solution code? Or does go-ios currently support multiple device connections?
