### ISSUE TITLE
The bundle “PlugIns” couldn’t be loaded

### ISSUE THREAD

**Issue by Rodionp13** [danielpaulus/go-ios#43]
Good day. Please, tell what I'm doing wrong or there's a real issue
XCUITest bundle built with Xcode 12.2 beta 3.
iPhone 12 Pro Max. iOS-14.3
iPhone 7. iOS-12.4

cmd:
./go-ios runtest "bundleID"
(app and xctest-runner have been already installed on device. app and xctest-runnder bundleIDs are fit naming convention:
bundleID && bundleIDUITests.xctrunner)

Output:
{"bundleID":"bundleIDUITests.xctrunner","channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Launching process","time":"2021-07-02T16:54:43+03:00"}
{"channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Process started successfully","pid":388,"time":"2021-07-02T16:54:43+03:00"}
{"level":"info","msg":"2021-07-02 16:54:43.915240+0300 BelfarmUITests-Runner[388:10124] Running tests...\n","time":"2021-07-02T16:54:44+03:00"}
{"level":"info","msg":"2021-07-02 16:54:43.926804+0300 BelfarmUITests-Runner[388:10124] **_The bundle “PlugIns” couldn’t be loaded because its executable couldn’t be located. Try reinstalling the bundle_**.\n","time":"2021-07-02T16:54:44+03:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_didFailToBootstrapWithError:","time":"2021-07-02T16:54:44+03:00"}
{"level":"error","msg":"DeviceConnection failed writing 402 bytes, only 0 sent","time":"2021-07-02T16:54:45+03:00"}
{"level":"error","msg":"Failed sending: write unix -\u003e/var/run/usbmuxd: write: broken pipe","time":"2021-07-02T16:54:45+03:00"}
{"channel_id":"dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface","error":"write unix -\u003e/var/run/usbmuxd: write: broken pipe","level":"info","methodselector":"_IDE_startExecutingTestPlanWithProtocolVersion:","msg":"failed starting invoking method","time":"2021-07-02T16:54:45+03:00"}

Structure of my xctrunner is straightforward: other resources including Plugins container(with *.xctest bundle) are presented.
I tried another sample app with XCUITest scheme with the only one test which loads application but the result is the same.
Thanks in advance.

**Comment by inluxc** [comment]
It should be same thing like this.

```
ios runwda --bundleid=com.facebook.WebDriverAgentRunner.xctrunner --testrunnerbundleid=com.facebook.WebDriverAgentRunner.xctrunner --xctestconfig=WebDriverAgentRunner.xctest
```

**Comment by nanoscopic** [comment]
go-ios does not work currently to start WDA on iPhone 7.
It needs to be updated to use a different method of starting WDA for that device.
Someone needs to capture what Xcode does to start WDA and provide Daniel Paulus with the dump of Xcode starting WDA on this device type so that he then has the information needed to implement it.

I've been meaning to do this ( provide the info ) but have not yet.
As a result, my own implementation of this, iosif, also has the same problem currently.

**Comment by danielpaulus** [comment]
The XCUITest/runwda part is a bit inconsistent as I built it with some time pressure. Let me know if the above suggestions fix it for you. Otherwise do what @nanoscopic  said and I can most likely resolve your issue :-)

**Comment by danielpaulus** [comment]
This one is resolved now. Sorry about that.
