### ISSUE TITLE
Start application or WDA with arguments

### ISSUE THREAD

**Issue by shamanec** [danielpaulus/go-ios#51]
Greetings,

Is there a possibility to start an application or the WebDriverAgent with provided arguments? Asking about WDA in particular, is it possible to provide USE_PORT argument for example so it starts on a specific port?

Best regards,
Nikola

**Comment by danielpaulus** [comment]
yes it is. I think I have not made it available to the command line. 
Let me add that in the next releases.

**Comment by shamanec** [comment]
That will be amazing, thanks!

**Comment by danielpaulus** [comment]
Should work now :-)

**Comment by shamanec** [comment]
Works perfect, thank you! This will be highly useful if also available on "ios runtest" and "ios launch" commands :)

**Comment by danielpaulus** [comment]
you are absolutely correct. I will add that next. Yesterday I fixed a bug in my pairing code and the `dproxy` command now finally works again for Instruments and Accessibility Inspector.

**Comment by danielpaulus** [comment]
Btw, if you have any other needs here, just let me know. Running subsets of tests etc. that can all be done. And thanks for sponsoring the project :-)

**Comment by shamanec** [comment]
Oh, I suppose you can't even buy lunch once with this, I wouldn't call it sponsoring :D I unfortunately can't afford a 100$ tier on a monthly basis but maybe with the help of your project I will, so for now I would not go over my head with requests :D  Right now I am more interested in the Appium testing applications of this because I can use it to run tests on iOS on Linux which can be cheaply scaled a lot more than the undescribably expensive Apple hardware, but I also take interest in the ability for XCUITests running that can make it a one-point solution for both native and Appium automation. I'll take the liberty of asking a few questions though:
 1. Is it possible to get performance data on a running application(or the device itself) like CPU usage/RAM usage for example?
 2. How does "ios runtest" work exactly by only providing the bundle ID of the test runner? Shouldn't it also require the bundle ID of the application that the test is running against?
 3. What do you mean by subsets of tests? Like target a specific scheme of the test runner?
 4. Is it okay if I integrate your project in the Appium docker for iOS project I am doing?
All in all I highly appreciate the amazing work you are doing on this and I am looking forward to seeing even more great features, hats off to you :)

**Comment by danielpaulus** [comment]
Haha, that is fine. I have not plans on getting rich with this, I am doing it mostly for fun :-D 
One thing I have thought about is building a small app to easily hook up iOS devices with CI servers. A problem I have right now for go-ios is that I have little to no integration tests. Ideally I would just connect an iOS device to github actions for that. 


To answer your questions:
1. Yes it is absolutely possible. Whatever you can do with the Mac, can be done with go-ios as well. I wanted to implement it at some point, shouldn't take more than a few hours. 
2. `testRunnerBundleID := bundleID + testBundleSuffix` where `const testBundleSuffix = "UITests.xctrunner"` you need the bundleId of the app, the runner follows a convention usually. This was done under some time pressure so it might not work well for wider use cases. I am happy to change these things though.
3. Exactly, Xcode allows you to only run a single testcase or ignore some
4. Sure! It is MIT license know, so you can do whatever you like with it :-) 
Have you seen this one? I started this for the appium conference talk I will give in September. 
https://github.com/danielpaulus/ios-appium-on-linux

**Comment by shamanec** [comment]
Sorry that I can't help you with writing the integration tests but if there is anything I can assist with in terms of testing stuff I am happy to help if I can :P 
 1. Wow, I didn't really think it as flexible as "whatever you can do with the Mac" 😮 
 2. Yeah, that makes sense. I saw another project that was asking for both and was just curious.
 3. Nice!
 4. Actually this is exactly the project that inspired me to start working on mine. I think I couldn't get it working at the time and now I am using another cli inside the containers, but I will switch to 'go-ios' and you are welcome to use any/all parts of it if it works for you :)

**Comment by danielpaulus** [comment]
1. Yes! I think the coolest part of go-ios is the dproxy command. If you start it, it will basically act as a man in the middle so it can intercept device<-> mac communication and decrypt the SSL connections. It dumps everything in a decoded format to files. So what I do is just, launch dproxy, do what I am interested in f.ex. change the zoom level of the screen with AX Inspector, look at the dproxy dump and then add it to go-ios :-D
