### ISSUE TITLE
curl post to JSON header 

### ISSUE THREAD

**Issue by man4567890** [danielpaulus/go-ios#65]
Hi,
We have deployed a number of devices using Device Farmer and MRX1203 repo for Apple Devices, but since the MRX1203 repo is not being supported anymore, we are trying to move to Control Floor for the Apple devices. With the MRX1203 repo we used the wda post to JSON_HEADER method and iproxy to control the screen for automated tests. For example
 
```
ps -ef | grep iproxy
501 46380 46365   0 Thu05PM ??         1:13.89 iproxy -s 0.0.0.0 -u 0000(8437645-000XXXXXXXXXXXXX 6127 8100

port_no=`ps -ef | grep iproxy | grep 0000(8437645-000XXXXXXXXXXXXX | grep 8100 | awk '{print $13}' | tail -1` 
echo $port_no
6127
 
JSON_HEADER='-H "Content-Type:application/json"'
DEVICE_URL=http://localhost:$port_no

# Return to home screen
curl -X POST $JSON_HEADER -d "" $DEVICE_URL/wda/homescreen

sleep 1

#GET session_id
SESSION_ID=`curl -X GET $JSON_HEADER $DEVICE_URL/status | grep sessionId`
SESSION_ID=`echo $SESSION_ID | awk '{print $3}'`
SESSION_ID=`echo $SESSION_ID | cut -d "\"" -f2`

sleep 1


# Open Messages screen
curl -X POST $JSON_HEADER -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.MobileSMS\"}}" $DEVICE_URL/wda/apps/launchapp

#get and tap Edit
edit=`curl -X POST $JSON_HEADER -d "{\"using\":\"link text\",\"value\":\"label=Edit\"}" $DEVICE_URL/session/$SESSION_ID/elements | grep ELEMENT`
edit=`echo $edit | awk '{print $3}'`
edit=`echo $edit | cut -d "\"" -f2`
echo $edit
curl -X POST $JSON_HEADER -d "" $DEVICE_URL/session/$SESSION_ID/element/$edit/click
```

My question, is it possible to do this with for example go-ios forward or go-iso dproxy? If so, how could I do this please
PS Extremely helpful cli, thanks for developing this!

**Comment by nanoscopic** [comment]
go-ios doesn't forward things over the internet. The forward command forwards data from a local port on the host machine to a port on the iOS device.

Current CF automatically starts a modified WDA that only responds via NNG ( Nanomsg Next Gen ). I have removed the HTTP connectivity from it and the majority of the normal commands  one would use to automate a device.

I have been told that another WDA ( normal Appium upstream ) can be run simultaneously on the device. I am working on adding support to do exactly that to CF currently.

What I also then need to add is a forwarding url on CF that can be used to send WDA commands to, that will automatically then send those WDA commands to the Appium WDA running on a device. This remains to be done.

In the short term it should be possible to start Appium WDA on a device already running in CF. Something like an ssh tunnel could then be used to let someone connect to the WDA port listening on the host machine where the iOS device is plugged in.

**Comment by man4567890** [comment]
Thanks David!

**Comment by danielpaulus** [comment]
Seems resolved.
