### ISSUE TITLE
Missing int64 primitive

### ISSUE THREAD

**Issue by nanoscopic** [danielpaulus/go-ios#67]
When attempting to use dproxy I get an error out of unarchiver. It corresponds to the following chunk of code in unarchiver.go:
```
//if this crashes, I forgot a primitive type
nonPrimitiveObjectRef := objectRef.(map[string]interface{})
```

The line above in the error message indicates it was an int64.
I added the following to the `isPrimitiveObject` function and it seems to resolve it:
```
if v, ok := object.(int64); ok {
	return v, ok
}
```

**Comment by danielpaulus** [comment]
This one will be fixed with https://github.com/danielpaulus/go-ios/pull/123
I am currently starting to implement cpu, memory etc. metrics

**Comment by danielpaulus** [comment]
fixed
