### ISSUE TITLE
runwda doesn't work on iOS 11

### ISSUE THREAD

**Issue by nanoscopic** [danielpaulus/go-ios#69]
I have created a parsed / rendered dump of the message stream used by Xcode to start WDA on an iOS 11 device:
https://dryark.com/ios11.htm

This was created by:

1. Creating a dtxproxy dump using go-ios ( I used an older machine where it still works )
2. Run `iosif ddf [folder of dump] > ios11.xml`
3. Run `iosif/dump.pl ios11.xml > ios11.htm`

**Comment by danielpaulus** [comment]
should work now
