### ISSUE TITLE
Is there a way to enable or disable the wifi?

### ISSUE THREAD

**Issue by felixruan** [danielpaulus/go-ios#70]
I want to enable or disable the wifi, is there a way to do this?

**Comment by danielpaulus** [comment]
The only way I can think of is by building a small xcuitest for that. You could run it easily with go-ios. 
Not the greatest solution, i know :-D

**Comment by danielpaulus** [comment]
closing this as I moved it to the Q&A here: https://github.com/danielpaulus/go-ios/discussions/90
