### ISSUE TITLE
Add ios uninstall <bundleID>

### ISSUE THREAD

**Issue by IntergalacticPenguin** [danielpaulus/go-ios#76]
Hello @danielpaulus, would you be interested in adding a new command `ios uninstall`?

It is currently supported by the old [ideviceinstaller](https://github.com/libimobiledevice/ideviceinstaller) implementation so I thought that you might consider adding it. 

It would be highly appreciated to be able to wipe devices when necessary.

Thank you for your hard work!

_As you might now I am currently trying to substitute libimobiledevice with your go-ios in [my own repo](https://github.com/IntergalacticPenguin/mobile-toolkit/pull/221), so I would really like to be able to retain all of the current features._

**Comment by danielpaulus** [comment]
hey there, I did not know about your plans before!
thanks for letting me know, I am always super excited to learn about why and what people are using go-ios for. 
Adding an uninstall command shouldn't be a big deal. I'll try to do it in the coming days.

**Comment by danielpaulus** [comment]
PS: let me know what else you need

**Comment by IntergalacticPenguin** [comment]
Cool, I'm super glad that there is finally some active development regarding open source iOS device management. 🎉 

We are using mobile toolkit while testing our applications at [@futured](https://github.com/futuredapp).

The biggest issue we have right now is being unable to record iOS device screen without doing manual work. 

There is an open source tool [videosnap](https://github.com/matthutchinson/videosnap) we used before, but since migration to M1 based macs, it stopped working. It is probably due to a problem only Apple can resolve. See this issue: https://github.com/matthutchinson/videosnap/issues/24

**Comment by danielpaulus** [comment]
Three options:
1. You can run go-ios screenshot in a loop, which is slow and unstable but works most of the time
2. use quicktime_video_hack (my other repo)
3. run webdriveragent with go ios and use the mjpeg streaming server

**Comment by danielpaulus** [comment]
PS: checked videosnap, seems like they use AV Capture device. I guess that is the same result as qvh. The only difference is that qvh also works on Linux and does not rely on any objectiveC APIs.

**Comment by danielpaulus** [comment]
it's done

**Comment by nanoscopic** [comment]
There are more options for video:
4. Use my ios_video_app repo ( or any other upload broadcast extension based method )
5. Use my ControlFloorAgent repo ( similar to WDA, but screenshot method is faster for the purpose of using as video )
6. Use an AirPlay2 open source destination service ( some open source ones exist )
7. Use an HDMI dongle + HDMI capture

**Comment by IntergalacticPenguin** [comment]
Thank you guys for provided leads. ❤️ 
I'll take a look at those later, when there will be enough time for research. 🙈
