### ISSUE TITLE
ios on windows install ipa files. error

### ISSUE THREAD

**Issue by kissfu** [danielpaulus/go-ios#79]
=== RUN   TestDeviceInstall
time="2021-12-20T14:14:17+08:00" level=info msg=installing appPath="D:\\workspace\\xxx.ipa" device=89ab5bbb40d90e29738be49f150f1c53ef54c972
time="2021-12-20T14:14:18+08:00" level=info msg=installing percentComplete=5 status=CreatingStagingDirectory
time="2021-12-20T14:14:18+08:00" level=info msg=installing percentComplete=15 status=ExtractingPackage
time="2021-12-20T14:14:18+08:00" level=info msg=installing percentComplete=20 status=InspectingPackage
time="2021-12-20T14:14:19+08:00" level=fatal msg="failed writing" err="failed installing: 'PackageInspectionFailed' errorDescription:'Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.1TG7lE/extracted/D:\\workspace\\xxx.ipa.app; Extra info about \"/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.1TG7lE/extracted/D:\\workspace\\xxx.ipa.app/Info.plist\": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.1TG7lE/extracted/D:\\workspace\\xxx.ipa.app/Info.plist: No such file or directory'"

**Comment by danielpaulus** [comment]
haha, damn. let's see if I can fix that.

**Comment by danielpaulus** [comment]
can you try https://github.com/danielpaulus/go-ios/pull/81 ?
I don'T have a windows machine, so unfortunately I cannot try myself atm. I could try and set up a vm but it is always a hassle.

**Comment by kissfu** [comment]
thanks very much .i will have a try and make a reply.

**Comment by danielpaulus** [comment]
it does not fix the issue. don't bother. I am working on fixing it currently. should only take a few days.
