### ISSUE TITLE
Deviceinfo doesn't work

### ISSUE THREAD

**Issue by nanoscopic** [danielpaulus/go-ios#9]
I cloned and built the repo.
I can run `./go-ios list` and the UUID of the IOS phone I have attached shows up.
I run `./go-ios info` and nothing is output, nor is any errorcode set.
I run `./go-ios info -u[my uuid]` and the same thing happens.
I run `./go-ios info -u=[my uuid]` and I get an error saying uuid `=[my uuid]` is not found.

Should I be expecting this to output some info? I feel like if something went wrong an error of any sort should be indicated/output.

Is there some other setup that I need to do before it will function? I currently have libusbmuxd and libimobiledevice installed. Would those interfere in some way?

One other detail: I am running this on Mac OS. Does it only work on Linux?

Update: I do see the PR for 'addDeviceInfo'. I checked out that branch and built it. Also does not work; same result as stated above.

**Comment by danielpaulus** [comment]
Can you please try again?
 Master was in a pretty WIP state recently. The command line parsing was broken and if the device was never paired, the tool would just hang forever. Also I added `-v` and `-t` switches for trace and verbose logging. 
So if it still does not work for you, please post the log output here :-D

**Comment by danielpaulus** [comment]
Fixed
