### ISSUE TITLE
Cannot pair supervised device

### ISSUE THREAD

**Issue by shamanec** [danielpaulus/go-ios#99]
**Describe the bug**
Attempting to pair a supervised device is not working

**To Reproduce**
1. Run ./ios pair --p12file=supervision.p12 --password=*********
2. First time it shows the "Trust" popup on the device.
3. I tap on "Trust" (although I don't think it should show in general?)
4. Second attempt it presents the following error:
{"err":"the response is missign the Error key: map[EscrowBag:[19 224 78 100 20 250 200 245 22 238 197 230 40 249 25 12 27 64 80 154 131 136 116 210 71 154 181 68 205 38 119 11] Request:Pair]","level":"fatal","msg":"Pairing failed","time":"2022-01-10T13:43:51+02:00"}

**Expected behavior**
Pairing a supervised device should not present "Trust" popup on device and should not return an error.

**Desktop (please complete the following information):**
 - OS: MacOS/Linux
 - Version v1.0.45

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2019
 - OS: 15.0

**Additional context**
The device was supervised using Apple Configurator 2 and the supervision identity file was extracted from there.

**Comment by danielpaulus** [comment]
Normally you should not have to do anything. It should just pair. Interesting. Let me try with different iOS versions.

**Comment by shamanec** [comment]
I am 98% sure I managed to perform a supervised pairing a few weeks ago but now I can't seem to do it even with an older release. I tried:
1. Older release of go-ios.
2. Reinstalling usbmuxd on the Linux host.
3. Re-supervising the device with Apple Configurator 2.
I can successfully pair with the unsupervised pairing. I am using the module in my own code and I can provide better debugging info so let me know if I could help with something :)

**Comment by danielpaulus** [comment]
As a matter of fact you can! 
if you could:
1. Close all apps that use the device
2. run `ios dproxy --binary` it will launch dproxy and create folder with dumps of all device-host communication for each connection. (run it in a empty directory of easier finding the created dirs)
3. run the supervised pairing command
4. ctrl+c dproxy
5. zip and send me the dump

**Comment by shamanec** [comment]
You got it!
[dumps.zip](https://github.com/danielpaulus/go-ios/files/7840540/dumps.zip)
 I'll reinstall my Ubuntu tomorrow just in case, although I get the same error on MacOS

**Comment by danielpaulus** [comment]
if you want to help me even further, 
from pair.go l:21
```
// here is how to turn a p12 into crt and key:
// openssl pkcs12 -in organization.p12 -out organization.pem -nodes -password pass:a
// openssl x509 -outform DER -out organization.crt -in organization.pem
// openssl rsa -outform DER -out organization.key -in organization.pem
// then you can run:
// cfgutil -K organization.key -C organization.crt pair
```
can you on a mac run this, also with dproxy enabled?
Then I can compare what cfgutil does differently.

**Comment by shamanec** [comment]
Sorry, I wasn't able to do that yesterday. I got a warning on the cfgutil command but I believe it was because of the key file permissions so I guess these dumps should be it:
[dump-2022.01.11-08.36.43.906.zip](https://github.com/danielpaulus/go-ios/files/7844932/dump-2022.01.11-08.36.43.906.zip)
Let me know if something is wrong or if I could help further!

**Comment by danielpaulus** [comment]
Yeah you need to run `chmod 600` on the key to make it work

**Comment by shamanec** [comment]
My bad, here's a new dump:
[dump-2022.01.11-08.43.10.459.zip](https://github.com/danielpaulus/go-ios/files/7844961/dump-2022.01.11-08.43.10.459.zip)

**Comment by danielpaulus** [comment]
good that you pointed it out! I will add it to the comments for next time :-)

**Comment by shamanec** [comment]
Here is the console output of the cfgutil pair just in case it might be useful:
objc[41439]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x7fff82f35830) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10a5c1c38). One of the two will be used. Which one is undefined.
objc[41439]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x7fff82f35880) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10a5c1c88). One of the two will be used. Which one is undefined.

Waiting for the device [1/1] [*******************************************]  100%
Paired with iPhone SE (2nd generation) (ECID: 0x418C136FB802E).

**Comment by danielpaulus** [comment]
Hm for some reason I cannot see the pairing happening in the cfgutil dump. 
I tried pairing my iPhone X 15.2 on Mac OS X with go-ios and it worked without any issues. 

can you get the cfgutil dump again please?

**Comment by danielpaulus** [comment]
The confusing thing is that it seems like your device already was paired. The Escrowbag usually is only sent when the pairing is completed. I wonder if I add a check for it and just complete the pairing, if everything will work. hmm

**Comment by danielpaulus** [comment]
Can you try https://github.com/danielpaulus/go-ios/pull/100 ?
(do you know how to compile?)

**Comment by shamanec** [comment]
Here are new dumps from dproxy when attempting cfgutil pair:
[dump-2022.01.12-05.37.42.341.zip](https://github.com/danielpaulus/go-ios/files/7851983/dump-2022.01.12-05.37.42.341.zip)
I tested with the fix branch:
1. First pair attempt it still shows the "Trust" popup.
2. After tapping "Trust" the first time, then on the second attempt it reports that pair was successful.
Is there a way to check if it was successfully paired? Also it should not have shown "Trust" the first time, right?

**Comment by shamanec** [comment]
Sooooo the problem was that my device was activation locked and Apple Configurator 2 was reporting that it supervised it but it wasn't actually finishing the supervision because of the lock... After removing activation lock and re-supervising the device it started working on the release branch... I am terribly, terribly sorry for losing your time, mate, but I didn't really expect that to be a problem because AC2 was saying the device is supervised. Thank your for attempting to help me but the fault was not on your side :)

**Comment by danielpaulus** [comment]
Hmm interesting. How did you detect it in the end? I wonder if I can add a check to go-ios for that case.

**Comment by shamanec** [comment]
More like trial and error - Apple Configurator 2 was saying that it cannot finalise activation due to activation lock but after that was reporting device is already supervised and needs to be reset again, so I just decided to remove account from device and reset and try again and this time around it worked. Not really sure how you can handle that but if you want I can attempt to reproduce it again and provide you the data on each step of 'PairSupervised'? Just let me know how I can assist you with that :)

**Comment by danielpaulus** [comment]
Hmm i was thinking maybe there is something to check activation status of the device. I dont think a repro is needed. We can also add it to the knowledgebase and leave it be 😁

**Comment by shamanec** [comment]
Cool :D Sorry again for the mess!

**Comment by danielpaulus** [comment]
Oh can you actually try and check `ios info` 
There is a few ActivationState properties in there. Maybe there is one we can use to identify improperly activated devices and issue a warning for future users. That'd be awesome.

**Comment by shamanec** [comment]
There is no difference in the fields you listed between the activated device and freshly reset(erase all content and settings) device. The only observable difference I saw is that the freshly reset device had these two additional fields in the info:
"ActivationStateAcknowledged": true
"UntrustedHostBUID": "56901EAC-0742-42C0-9909-22203DD488D8"

**Comment by danielpaulus** [comment]
hm yeah that does not seem to work as an indicator. Thanks for looking into it and for reporting the issue :-) 
I am closing it now.
